name=XC Hardware
version=1.0.0
author=iv600
maintainer=iv660
sentence=The library for XC game appliances
paragraph=A library containing definitions for hardware appliances of the XC game consoles series
category=Games
architectures=*
